name: cs236605-hw
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pytorch=0.4
  - torchvision
  - jupyterlab=0.34
  - numpy=1.15
  - scikit-learn=0.19
  - ipython
  - jupyter
  - pandas
  - cython
  - pytest
  - pip:
    - matplotlib~=3.0
    - nbmerge
    - pytest-xdist
